import {
  AppWindow,
  Award,
  Bot,
  Briefcase,
  Camera,
  FileText,
  GitBranch,
  Globe,
  Image as ImageIcon,
  PackageSearch,
  PenTool,
  PlayCircle,
  Presentation,
  Smartphone,
  Video,
  type LucideIcon,
} from "lucide-react";
import type { MediaAssetType } from "@/content/journey";

export const MEDIA_TYPE_ICONS: Record<MediaAssetType, LucideIcon> = {
  website: Globe,
  prototype: PenTool,
  presentation: Presentation,
  poster: ImageIcon,
  prd: FileText,
  screenshot: Camera,
  demo: PlayCircle,
  github: GitBranch,
  video: Video,
  activity: Briefcase,
  botActivity: Bot,
  product: PackageSearch,
  logo: Award,
  androidApp: Smartphone,
  miniApp: AppWindow,
};

export const MEDIA_TYPE_LABELS: Record<MediaAssetType, string> = {
  website: "Website",
  prototype: "Prototype",
  presentation: "Presentation",
  poster: "Poster",
  prd: "PRD",
  screenshot: "Screenshot",
  demo: "Demo",
  github: "GitHub",
  video: "Video",
  activity: "Activity",
  botActivity: "Bot Activity",
  product: "Product",
  logo: "Logo",
  androidApp: "Android App",
  miniApp: "MiniApp",
};
